var shortTimes = {"af-za":"hh:mm tt",
                  "ar-ae":"hh:mm tt",
                  "ar-bh":"hh:mm tt",
                  "ar-dz":"H:mm",
                  "ar-eg":"hh:mm tt",
                  "ar-iq":"hh:mm tt",
                  "ar-jo":"hh:mm tt",
                  "ar-kw":"hh:mm tt",
                  "ar-lb":"hh:mm tt",
                  "ar-ly":"hh:mm tt",
                  "ar-ma":"H:mm",
                  "ar-om":"hh:mm tt",
                  "ar-qa":"hh:mm tt",
                  "ar-sa":"hh:mm tt",
                  "ar-sy":"hh:mm tt",
                  "ar-tn":"H:mm",
                  "ar-ye":"hh:mm tt",
                  "az-cyrl-az":"H:mm",
                  "az-latn-az":"H:mm",
                  "be-by":"H:mm",
                  "bg-bg":"HH:mm",
                  "bs-latn-ba":"H:mm:ss",
                  "ca-es":"HH:mm",
                  "cs-cz":"H:mm",
                  "cy-gb":"HH:mm:ss",
                  "da-dk":"HH:mm",
                  "de-at":"HH:mm",
                  "de-ch":"HH:mm",
                  "de-de":"HH:mm",
                  "de-li":"HH:mm",
                  "de-lu":"HH:mm",
                  "dv-mv":"HH:mm",
                  "el-gr":"h:mm tt",
                  "en-029":"h:mm tt",
                  "en-au":"h:mm tt",
                  "en-bz":"hh:mm tt",
                  "en-ca":"h:mm tt",
                  "en-gb":"HH:mm",
                  "en-ie":"HH:mm",
                  "en-jm":"hh:mm tt",
                  "en-nz":"h:mm tt",
                  "en-ph":"h:mm tt",
                  "en-tt":"hh:mm tt",
                  "en-us":"h:mm tt",
                  "en-za":"hh:mm tt",
                  "en-zw":"h:mm tt",
                  "es-ar":"hh:mm tt",
                  "es-bo":"hh:mm tt",
                  "es-cl":"H:mm",
                  "es-co":"hh:mm tt",
                  "es-cr":"hh:mm tt",
                  "es-do":"hh:mm tt",
                  "es-ec":"H:mm",
                  "es-es":"H:mm",
                  "es-gt":"hh:mm tt",
                  "es-hn":"hh:mm tt",
                  "es-mx":"hh:mm tt",
                  "es-ni":"hh:mm tt",
                  "es-pa":"hh:mm tt",
                  "es-pe":"hh:mm tt",
                  "es-pr":"hh:mm tt",
                  "es-py":"hh:mm tt",
                  "es-sv":"hh:mm tt",
                  "es-uy":"hh:mm tt",
                  "es-ve":"hh:mm tt",
                  "et-ee":"H:mm",
                  "eu-es":"HH:mm",
                  "fa-ir":"hh:mm tt",
                  "fi-fi":"H:mm",
                  "fo-fo":"HH.mm",
                  "fr-be":"H:mm",
                  "fr-ca":"HH:mm",
                  "fr-ch":"HH:mm",
                  "fr-fr":"HH:mm",
                  "fr-lu":"HH:mm",
                  "fr-mc":"HH:mm",
                  "gl-es":"H:mm",
                  "gu-in":"HH:mm",
                  "he-il":"HH:mm",
                  "hi-in":"HH:mm",
                  "hr-ba":"H:mm:ss",
                  "hr-hr":"H:mm",
                  "hu-hu":"H:mm",
                  "hy-am":"H:mm",
                  "id-id":"H:mm",
                  "is-is":"HH:mm",
                  "it-ch":"HH:mm",
                  "it-it":"H.mm",
                  "ja-jp":"H:mm",
                  "ka-ge":"H:mm",
                  "kk-kz":"H:mm",
                  "kn-in":"HH:mm",
                  "ko-kr":"tt h:mm",
                  "kok-in":"HH:mm",
                  "ky-kg":"H:mm",
                  "lt-lt":"HH:mm",
                  "lv-lv":"H:mm",
                  "mi-nz":"h:mm:ss tt",
                  "mk-mk":"HH:mm",
                  "mn-mn":"H:mm",
                  "mr-in":"HH:mm",
                  "ms-bn":"H:mm",
                  "ms-my":"H:mm",
                  "mt-mt":"HH:mm:ss",
                  "nb-no":"HH:mm",
                  "nl-be":"H:mm",
                  "nl-nl":"H:mm",
                  "nn-no":"HH:mm",
                  "ns-za":"hh:mm:ss tt",
                  "pa-in":"tt hh:mm",
                  "pl-pl":"HH:mm",
                  "pt-br":"H:mm",
                  "pt-pt":"H:mm",
                  "quz-bo":"hh:mm:ss tt",
                  "quz-ec":"H:mm:ss",
                  "quz-pe":"hh:mm:ss tt",
                  "ro-ro":"HH:mm",
                  "ru-ru":"H:mm",
                  "sa-in":"HH:mm",
                  "se-fi":"H:mm:ss",
                  "se-no":"HH:mm:ss",
                  "se-se":"HH:mm:ss",
                  "sk-sk":"H:mm",
                  "sl-si":"H:mm",
                  "sma-no":"HH:mm:ss",
                  "sma-se":"HH:mm:ss",
                  "smj-no":"HH:mm:ss",
                  "smj-se":"HH:mm:ss",
                  "smn-fi":"H:mm:ss",
                  "sms-fi":"H:mm:ss",
                  "sq-al":"h:mm.tt",
                  "sr-cyrl-ba":"H:mm:ss",
                  "sr-cyrl-cs":"H:mm",
                  "sr-latn-ba":"H:mm:ss",
                  "sr-latn-cs":"H:mm",
                  "sv-fi":"HH:mm",
                  "sv-se":"HH:mm",
                  "sw-ke":"h:mm tt",
                  "syr-sy":"hh:mm tt",
                  "ta-in":"HH:mm",
                  "te-in":"HH:mm",
                  "th-th":"H:mm",
                  "tn-za":"hh:mm:ss tt",
                  "tr-tr":"HH:mm",
                  "tt-ru":"H:mm",
                  "uk-ua":"H:mm",
                  "ur-pk":"h:mm tt",
                  "uz-cyrl-uz":"HH:mm",
                  "uz-latn-uz":"HH:mm",
                  "vi-vn":"h:mm tt",
                  "xh-za":"hh:mm:ss tt",
                  "zh-cn":"H:mm",
                  "zh-hk":"H:mm",
                  "zh-mo":"H:mm",
                  "zh-sg":"tt h:mm",
                  "zh-tw":"tt hh:mm",
                  "zu-za":"hh:mm:ss tt"};
