var tz =      {
               "BST    (GMT+1)":3600,
               "CEST   (GMT+2)":7200,
               "CET    (GMT+1)":3600,
               "EEST   (GMT+3)":10800,
               "EET    (GMT+2)":7200,
               "EST    (GMT-5)":-18000,
               "GMT-12"        :-43200,
               "GMT-11"        :-39600,
               "GMT-10"        :-36000,
               "GMT-9"         :-32400,
               "GMT-8"         :-28800,
               "GMT-7"         :-25200,
               "GMT-6"         :-21600,
               "GMT-5"         :-18000,
               "GMT-4"         :-14400,
               "GMT-3"         :-10800,
               "GMT-2"         :-7200,
               "GMT-1"         :-3600,
               "GMT"           :0,
               "GMT+1"         :3600,
               "GMT+2"         :7200,
               "GMT+3"         :10800,
               "GMT+4"         :14400,
               "GMT+5"         :18000,
               "GMT+6"         :21600,
               "GMT+7"         :25200,
               "GMT+8"         :28800,
               "GMT+9"         :32400,
               "GMT+10"        :36000,
               "GMT+11"        :39600,
               "GMT+12"        :43200,
               "HKT    (GMT+8)":28800,
               "KST    (GMT+9)":32400,
               "PDT    (GMT-7)":-25200,
               "PST    (GMT-8)":-28800,
               "WDT    (GMT+9)":32400,
               "WEST   (GMT+1)":3600,
               "WET    (GMT)"  :0,
               "WST    (GMT+8)":28800,
};

var tznames = {
               "BST" : "British Summer Time",
               "CET" : "Central European Time",
               "CEST" : "Central European Summer Time",
               "EET" : "Eastern European Time",
               "EEST" : "Eastern European Summer Time",
               "EST" : "Eastern Standard Time",
               "HKT"  : "Hong Kong Time",
               "KST" : "Korea Standard Time",
               "PDT" : "Pacific Daylight Time",
               "PST" : "Pacific Standard Time",
               "WDT" : "Western Daylight Time",
               "WEST" : "Western European Summer Time",
               "WET" : "Western European Time",
               "WST" : "Western Standard Time",
};

