var tz =      {"ACDT":37800,
               "ACST":34200,
               "ADT ":-10800,
               "AEDT":39600,
               "AEST":36000,
               "AKDT":-28800,
               "AKST":-32400,
               "AST ":-14400,
               "AWDT":32400,
               "AWST":28800,
               "BST ":3600,
               "CDT ":-18000,
               "CEDT":7200,
               "CEST":7200,
               "CET ":3600,
               "CST ":-21600,
               "CXT ":25200,
               "EDT ":-14400,
               "EEDT":10800,
               "EEST":10800,
               "EET ":7200,
               "EST ":-18000,
               "GMT ":0,
               "HADT":-32400,
               "HAST":-36000,
               "HST ":-36000,
               "IST ":3600,
               "KST ":32400,
               "MDT ":-21600,
               "MESZ":7200,
               "MEZ ":3600,
               "MSD ":14400,
               "MSK ":10800,
               "MST ":-25200,
               "NDT ":-9000,
               "NFT ":41400,
               "NST ":-12600,
               "NZST":43200,
               "NZDT":46800,
               "PDT ":-25200,
               "PST ":-28800,
               "UTC ":0,
               "WDT ":32400,
               "WEDT":3600,
               "WEST":3600,
               "WET ":0,
               "WST ":28800
};

var tznames = {"CEDT" : "Central European Daylight Time",
               "CEST" : "Central European Summer Time",
               "EDT " : "Eastern Daylight Time",
               "EST " : "Eastern Standard Time",
               "PDT " : "Pacific Daylight Time",
               "PST " : "Pacific Standard Time",
               "MDT " : "Mountain Daylight Time",
               "MST " : "Mountain Standard Time",
               "CDT " : "Central Daylight Time",
               "CST " : "Central Standard Time",
               "NZST" : "New Zealand Standard Time",
               "NZDT" : "New Zealand Daylight Time",
               "ACDT" : "Australian Central Daylight Time",
               "ACST" : "Australian Central Standard Time",
               "ADT " : "Atlantic Daylight Time",
               "AEDT" : "Australian Eastern Daylight Time",
               "AEST" : "Australian Eastern Standard Time",
               "AKDT" : "Alaska Daylight Time",
               "AKST" : "Alaska Standard Time",
               "AST " : "Atlantic Standard Time",
               "AWDT" : "Australian Western Daylight Time",
               "AWST" : "Australian Western Standard Time",
               "BST " : "British Summer Time",
               "CET " : "Central European Time",
               "CXT " : "Christmas Island Time",
               "EEDT" : "Eastern European Daylight Time",
               "EEST" : "Eastern European Summer Time",
               "EET " : "Eastern European Time",
               "GMT " : "Greenwich Mean Time",
               "HADT" : "Hawaii-Aleutian Daylight Time",
               "HAST" : "Hawaii-Aleutian Standard Time",
               "HST " : "Hawaii Standard Time",
               "IST " : "Irish Summer Time",
               "KST " : "Korea Standard Time",
               "MESZ" : "Mitteleuropäische Sommerzeit",
               "MEZ " : "Mitteleuropäische Zeit",
               "MSD " : "Moscow Daylight Time",
               "MSK " : "Moscow Standard Time",
               "NDT " : "Newfoundland Daylight Time",
               "NFT " : "Norfolk Island Time",
               "NST " : "Newfoundland Standard Time",
               "UTC " : "Coordinated Universal Time",
               "WDT " : "Western Daylight Time",
               "WEDT" : "Western European Daylight Time",
               "WEST" : "Western European Summer Time",
               "WET " : "Western European Time",
               "WST " : "Western Standard Time"
};

